# Generated by Django 5.0 on 2023-12-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='qr_code_url',
            field=models.URLField(blank=True),
        ),
    ]
