# Generated by Django 5.0.1 on 2024-06-28 10:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_building_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorizationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('ENTIRE', 'Entire Building'), ('PARTIAL', 'Selected Rooms')], max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='ACTIVE', max_length=10)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.building')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_inventorizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InventorizationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('inventorization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='devices.inventorizationlist')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.room')),
            ],
        ),
        migrations.CreateModel(
            name='InventorizationDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_scanned', models.BooleanField(default=False)),
                ('scan_date', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('inventorization_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.inventorizationroom')),
            ],
        ),
    ]
