# Generated by Django 5.0 on 2023-12-19 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_qr_code_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('acronym', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='qr_code_url',
        ),
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.CharField(default=-1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='is_qrcode_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='qrcode_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='building',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='devices.building'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveIntegerField(unique=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.building')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='floor',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='devices.floor'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=5)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.building')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.floor')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='devices.room'),
            preserve_default=False,
        ),
    ]
