# Generated by Django 5.0.1 on 2024-06-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_inventorizationlist_inventorizationroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorizationlist',
            name='room_ids',
            field=models.JSONField(default=list),
        ),
    ]
