# Generated by Django 5.0.1 on 2024-06-28 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_inventorizationlist_room_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.inventorizationlist')),
            ],
            options={
                'unique_together': {('inventory', 'device')},
            },
        ),
    ]
