# Generated by Django 5.0 on 2023-12-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='qrcode_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
