# Generated by Django 5.0.1 on 2024-07-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alter_inventorizationlist_status_extendeduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='building',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='faculty',
            field=models.CharField(blank=True, choices=[('AC', 'Faculty of Automatic Control & Computer Engineering'), ('EE', 'Faculty of Electrical Engineering'), ('ETTI', 'Faculty of Electronics, Telecommunications & Information Technology'), ('CEBS', 'Faculty of Civil Engineering & Building Services'), ('CEEP', 'Faculty of „Cristofor Simionescu” Chemical Engineering & Environmental Protection'), ('MMIM', 'Faculty of Machine Manufacturing & Industrial Management'), ('ARCH', 'Faculty of „G. M. Cantacuzino” Architecture'), ('HGEE', 'Faculty of Hydrotechnics, Geodesy & Environmental Engineering'), ('ME', 'Faculty of Mechanical Engineering'), ('SIM', 'Material Science & Engineering'), ('IDBM', 'Industrial Design and Business Management')], max_length=4),
        ),
    ]
