# Generated by Django 5.0 on 2023-12-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_subcategory_device_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_number',
            new_name='name',
        ),
    ]
