# Generated by Django 5.0.1 on 2024-07-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_remove_extendeduser_building_extendeduser_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='admin_rank',
            field=models.CharField(blank=True, choices=[('RECTOR', 'Rector'), ('PRORECTOR', 'Vice-rector'), ('DECAN', 'Decan (Dean)'), ('PRODECAN', 'Prodecan (Vice-dean)'), ('DIR_DEPT', 'Director de departament (Head of department)'), ('SEF_DISC', 'Șef de disciplină (Head of a subject)'), ('None', 'None')], max_length=20),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='rank',
            field=models.CharField(blank=True, choices=[('PROF', 'Profesor (Professor)'), ('CONF', 'Conferentiar (Associate Professor)'), ('LECTOR', 'Șef lucrări (Lecturer)'), ('ASIST', 'Asistent universitar (Assistant)'), ('ENG', 'Engineer'), ('None', 'None')], max_length=20),
        ),
    ]
