# Generated by Django 5.0.1 on 2024-07-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_alter_extendeduser_admin_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='acronym_rank',
            field=models.CharField(blank=True, choices=[('PROF', 'Prof.dr.ing.'), ('CONF', 'Conf.dr.ing.'), ('LECTOR', 'Șef lucrări dr.ing.'), ('ASIST', 'Asist.dr.ing.'), ('ENG', 'Eng.'), ('None', 'None')], max_length=20),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='faculty',
            field=models.CharField(blank=True, choices=[('AC', 'Faculty of Automatic Control & Computer Engineering'), ('EE', 'Faculty of Electrical Engineering'), ('ETTI', 'Faculty of Electronics, Telecommunications & Information Technology'), ('CEBS', 'Faculty of Civil Engineering & Building Services'), ('CEEP', 'Faculty of „Cristofor Simionescu” Chemical Engineering & Environmental Protection'), ('MMIM', 'Faculty of Machine Manufacturing & Industrial Management'), ('ARCH', 'Faculty of „G. M. Cantacuzino” Architecture'), ('HGEE', 'Faculty of Hydrotechnics, Geodesy & Environmental Engineering'), ('ME', 'Faculty of Mechanical Engineering'), ('SIM', 'Faculty of Material Science & Engineering'), ('IDBM', 'Faculty of Industrial Design and Business Management')], max_length=4),
        ),
    ]
