# Generated by Django 5.0.1 on 2024-07-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_extendeduser_acronym_rank_alter_extendeduser_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='qrcode_url',
            new_name='qrcode_path',
        ),
        migrations.AddField(
            model_name='device',
            name='qrcode_target_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
