# Generated by Django 5.0.1 on 2024-07-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_rename_qrcode_url_device_qrcode_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorizationlist',
            name='room_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='inventorizationlist',
            name='total_devices',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorizationlist',
            name='total_scanned',
            field=models.IntegerField(default=0),
        ),
    ]
