# Generated by Django 5.0.1 on 2024-07-14 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_device_inventory_inventorychange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorychange',
            name='action',
        ),
        migrations.AddField(
            model_name='inventorizationlist',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.inventory'),
        ),
        migrations.AddField(
            model_name='inventorychange',
            name='change_type',
            field=models.CharField(blank=True, choices=[('ADD', 'Add'), ('REMOVE', 'Remove'), ('EDIT', 'Edit')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inventorychange',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
